### ISSUE TITLE
Notebook refresh error when creating multiple imagepoly visualizations

### ISSUE THREAD

**Issue by freeman-lab** [lightning-viz/lightning#17]
When generating multiple imagepoly visualizations, and with lightning's notebook open, only the first visualization appears, and there's an error rendering the subsequent ones. To reproduce, just call this sequence from the python client, with the lightning notebook session open and visible:

```
img = random.randn(100,200)
p = [[[0,0],[0,50],[50,50],[50,0]], [[50,50],[50,100],[1000,100],[100,50]]]

lgn.imagepoly(img, p)
lgn.imagepoly(img, p)
lgn.imagepoly(img, p)
```
Only the first will appear, and the second two each trigger a `Uncaught TypeError: Cannot read property 'indexOf' of undefined` error. Refreshing the page shows all visualizations properly.

Posting here because it manifests as a bug in the notebook, but it may be related to the viz type itself.

**Comment by mathisonian** [comment]
this one seems to have been fixed
