### ISSUE TITLE
Use canvas for scatter and line

### ISSUE THREAD

**Issue by freeman-lab** [lightning-viz/lightning#24]
Opening this up for discussion rather than a full PR yet. 

I've rewritten line and scatter to use canvas instead of SVG, see here:

https://github.com/freeman-lab/line-canvas
https://github.com/freeman-lab/scatter-canvas

After a lot of experimenting, I've identified several pros/cons to switching to canvas for these charts (and possibly others that are still SVG):

Pros
- We can keep the nice d3 zooming and axis handling 
- The plots themselves look essentially identical
- Performance in notebooks (e.g. IPython) is hugely improved. *This is the game changer*. Whereas before having even six or seven charts of moderate complexity in a single notebook crumbled the page, now you can just keep making charts forever and no slow down.
- Drawing performance and zooming is reasonable, but not dramatically improved. Frustratingly, a lot of the bottleneck seems to be math related to stroke thickness greater than 1 (e.g. http://stackoverflow.com/questions/21105829/why-does-ctx-linewidth-1-make-batched-line-drawing-slow). I do think there are opportunities for further optimization.

Cons
- Hover effects will be less straightforward (and I haven't implemented them), though we aren't doing much with them for these charts anyway (compared to, say, the graphs)
- Appending will be less straightforward (and I haven't implemented it). 
- `line-streaming` and `scatter-streaming` now extend `scatter` and `line`, so would need redesigns.

I see at least two options:

1) Replace the current `line` and `scatter` with their canvas versions, and make `scatter-streaming` and `scatter-line` separate pure SVG versions (with a plan to replace with canvas in the future).

2) Add `line-canvas` and `scatter-canvas` as new, optional, chart types, and perhaps provide the choice as an option to the client libraries.

**Comment by mathisonian** [comment]
I'm bullish on this. I think the pros far outweigh the cons and even considering the drawbacks I don't see much regressions compared to the current implementation. I don't think hover effects are super important for these types, but there are still ways to implement this if we find they are necessary. 

I'd vote against adding them as `X-canvas` chart types and instead move to replace the current implementations.

Curious to hear what others think on this.

**Comment by sofroniewn** [comment]
I'm psyched.

**Comment by freeman-lab** [comment]
Closing, as these updates have happened (or are being tracked) on the [`lightning-default-visualizations`](https://github.com/lightning-viz/lightning-default-visualizations) repo
