### ISSUE TITLE
"Take Screenshot" crashes local server

### ISSUE THREAD

**Issue by cxhernandez** [lightning-viz/lightning#29]
Whenever I try to save my visualizations as images, the server crashes and dumps this cryptic error:

```javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
24 Jun 00:30:22 - [nodemon] app crashed - waiting for file changes before starting...
```

I'm running a local sever on Linux 3.16.0-4-amd64 SMP Debian 3.16.7-ckt9-3 (2015-04-23) x86_64 GNU/Linux.

**Comment by mathisonian** [comment]
Hey @cxhernandez,

Is there anything else in the stacktrace or is this the whole thing? 

We are using https://github.com/brenden/node-webshot under the hood, so I wonder if there's an incompatibility happening there.

**Comment by mathisonian** [comment]
I've pushed an explicit error handler to master, if you pull the latest hopefully the error output will be more informative.

**Comment by cxhernandez** [comment]
@mathisonian thanks for your help! I just installed the latest version of master, and the issue somehow resolved itself. Must've been some screw up on my part during the last installation.

**Comment by mathisonian** [comment]
Cool, glad it was resolved! Feel free to post more issues as anything comes up
