### ISSUE TITLE
Graphs needs to have vertex labels

### ISSUE THREAD

**Issue by rejithry** [lightning-viz/lightning#30]
Complex graphs are difficult to reason about without vertex labels. A vertex label while creating the graph would be ideal.

**Comment by freeman-lab** [comment]
Thanks for the feedback! I'm currently finishing a redesign of all the graph-related viz types (using canvas for improved performance) and will add an option for vertex labels.

**Comment by freeman-lab** [comment]
This is now available, see the pull request at https://github.com/lightning-viz/lightning-force/pull/3
