### ISSUE TITLE
Updates to custom visualization structure and editor

### ISSUE THREAD

**Issue by mathisonian** [lightning-viz/lightning#31]
Posting this to open a discussion.

I am working on a large update to the way that lightning loads custom visualizations. Particularly I'm adding support to load via the [npm registry](https://www.npmjs.com/) in the [npm-modules](https://github.com/lightning-viz/lightning/tree/npm-modules) branch.

Using npm for this has a few key benefits:

* **Dependency specification per visualization** - each visualization can specify it's own dependency tree instead of relying on libraries installed on the server.
* **No more enforcement of a particular file structure** - Visualizations can be written in any structure as long as they implement certain methods. This is good because they are no longer restricted to a single javascript file (@brianbreitsch was hitting this limitation I believe)
* **Reduced complexity of compilation and dependency management** - especially with linked plots we were seeing a lot of small bugs around this. Using npm/node_modules cleans this up significantly.
* **Easier local development** - by using `npm link` visualizations can be customized in your favorite editor/ide and the changes will immediately be propagated to a local lightning server.
* **Search** - the server will be able to search the registry for modules with the tag `lightning-visualization` and generate an autocompleting field of user submitted visualizations that can be imported.

As of now these changes are not breaking and the ability to load custom visualizations using the old folder structure hasn't been removed. However, I am in favor of deprecating this eventually.

A bigger question is how to update the code editor.

So, **if you are a person who uses the editor for anything, please chime in, even if its just to let us know how you are using it**.

The main issue is that currently the editor relies on visualizations all conforming to a certain folder structure. With the removal of this invariant, we have to rethink how the editor functions. There two realistic options as I see it:

1. Remove the code editing functionality altogether. The editor would then just support sample data, and would become more of a 'data playground', giving a web interface to test loading in data sets to various visualizations.
2. Add a lightweight file browser. The editor would then still allow you to edit javascript files, but the interface would be more complex.

Personally I am in favor of (1) just because in my own workflow I have found that more often than not, any changes I would be using the web editor for I end up doing in a local IDE, but I am curious if others have the same experience.

Please comment with thoughts, concerns, examples of how you are using lightning, etc.

/cc @freeman-lab

**Comment by mathisonian** [comment]
See https://github.com/lightning-viz/lightning-hexbin for an example custom visualization that could be included via npm

**Comment by micahstubbs** [comment]
Great to this idea fleshed out in a post.  I'm curious, in the example, what roles do `lib/components/hexbin.js` and `src/components/hexbin.js` play?  Imagine there is something for me to learn there about the structure of a React app (or a node module).

**Comment by mathisonian** [comment]
@micahstubbs the `lib` and `src` folders there are just a side effect of writing in the React jsx style. All development is done in `src` and then it gets compiled to standard ES5 syntax in `lib`

**Comment by micahstubbs** [comment]
ah, got it now! 

...

If we remove the in-lighting vis code editor, I'd like to see a quick guide that says something like *to swap out this view for a custom vis type, do this:*

1. fork this repo
2. edit the vis code in these .js files
3. run this build script to publish your vis fork as a node module
4. paste the link of the node module for your new vis type here

**Comment by freeman-lab** [comment]
Closed by https://github.com/lightning-viz/lightning/pull/42
