### ISSUE TITLE
Bug when creating thumbnail path

### ISSUE THREAD

**Issue by mistycheney** [lightning-viz/lightning#32]
In `lightning/app/controllers/session.js`, line 510 should be
`thumbnailPath = path.dirname(imgPath) + '/' + filenameWithoutExtension + '_thumbnail' + extension;`

Otherwise, `thumbnailPath` will be incorrect. This results in the gallery visualization working only against a Heruko server, but not a local server.

**Comment by mathisonian** [comment]
Good catch, thanks!
