### ISSUE TITLE
Javascript SyntaxError when setting up server with ipython=True

### ISSUE THREAD

**Issue by mistycheney** [lightning-viz/lightning#33]
When I run these in ipython notebook
```
host = 'https://powerful-gorge-4659.herokuapp.com/'
auth = ('', '')
lgn = Lightning(ipython=True, host=host, auth=auth)
```

I got the warning,
```
Javascript error adding output!
SyntaxError: Unexpected token <
See your browser Javascript console for more details.
```

The server continues to work normally though.

If ipython=False, then there is no warning.

**Comment by mathisonian** [comment]
@mistycheney it looks like the "deploy to heroku" button was pointing to an old release (assuming you deployed via that?)

Could you redeploy using this link https://heroku.com/deploy?template=https://github.com/lightning-viz/lightning/tree/v0.1.13 and see if the problem goes away?

**Comment by mistycheney** [comment]
Yes, the warning disappears. Thanks.

**Comment by mathisonian** [comment]
Cool :v: thanks!
