### ISSUE TITLE
Region drawing tool does not show up

### ISSUE THREAD

**Issue by mistycheney** [lightning-viz/lightning#34]
The region drawing cross did not show up in both Firefox and Chrome, as you can see [here](https://obscure-shore-8000.herokuapp.com/sessions/3/public/). I only have the hand icon for dragging.

However in the [example page] (http://nbviewer.ipython.org/github/lightning-viz/lightning-example-notebooks/blob/master/images/images.ipynb) I can draw regions without a problem.

**Comment by mathisonian** [comment]
@mistycheney, have you had any luck getting this to work? Sorry for the delayed response.

The link seems to be down for me.

**Comment by mathisonian** [comment]
I'm not sure if you are using the [python-client](https://github.com/lightning-viz/lightning-python) but I was able to produce working plots including the region drawing tool with the following example

```python
from lightning import Lightning
lgn = Lightning()

lgn.imagepoly([[1, 2], [3, 3]])
```
