### ISSUE TITLE
Small typo on http://lightning-viz.org/documentation/

### ISSUE THREAD

**Issue by peteflorence** [lightning-viz/lightning#36]
Hello! Thought might be helpful to point out a little typo at http://lightning-viz.org/documentation/
Please let me know if there's a preferred place to provide feedback on the documentation?

```
from lighting import Lightning
lgn = Lightning()
```

"lightning" is mispelled -- tripped me up for a minute or two since thought it wasn't installed!

**Comment by mathisonian** [comment]
Fixed, thanks for pointing this out! Please let us know if you notice any other mistakes or confusing parts of the documentation. The source is here https://github.com/lightning-viz/lightning-viz.github.io/tree/src

**Comment by peteflorence** [comment]
Sounds good, thanks
