### ISSUE TITLE
wrong code in the documentation

### ISSUE THREAD

**Issue by nblintao** [lightning-viz/lightning#37]
http://lightning-viz.org/documentation/#initialize-python
There is a typo in the code of importing lightning:
`from lighting import Lightning`
It should be `lightning` rather than `lighting`

**Comment by mathisonian** [comment]
Fixed, thanks for pointing this out! 

Please let us know if you notice any other mistakes or confusing parts of the documentation. The source is here https://github.com/lightning-viz/lightning-viz.github.io/tree/src
