### ISSUE TITLE
Add bundle

### ISSUE THREAD

**Issue by freeman-lab** [lightning-viz/lightning#38]
We should provide a bundled version of the js/css for all the viz types so that client libraries (e.g. Python) can run in "headless" mode without a running server. This could work by grabbing all the npm modules specified in our "default visualizations" config (as soon as everything is in npm), and then we'll embed the js/css in release updates to the client libraries.

**Comment by mathisonian** [comment]
Tooling to generate the standalone bundle was added. To generate the bundle run `npm run generate-standalone-js`. This will create the bundle with whatever visualizations are currently installed on the local server
