### ISSUE TITLE
Name conflicts when importing

### ISSUE THREAD

**Issue by colesimmons** [lightning-viz/lightning#40]
When importing from http://localhost:3000/visualization-types/preview/?path=path/to/viz (http://localhost:3000/visualization-types/preview/?path=lightning-default-visualizations/map for example), if there already exists a visualization with the name I choose, it silently shits itself with a

```
POST http://localhost:3000/visualizations/types/ 500 (Internal Server Error)
fake_1eae9067.js:72 Uncaught TypeError: Cannot read property 'id' of null
```

**Comment by mathisonian** [comment]
thanks for reporting! added some more informative error handling in 670cc631746e02ea557d2a8a10a8a671eb503101
