### ISSUE TITLE
Importing local folder from editor screen fails to include .jade file

### ISSUE THREAD

**Issue by colesimmons** [lightning-viz/lightning#41]
When importing a visualization from http://localhost:3000/visualization-types/preview/?path=path/to/viz (http://localhost:3000/visualization-types/preview/?path=lightning-default-visualizations/map/ for example), it imports, but on the following screen I get the following in the browser console:

```
GET http://localhost:3000/js/dynamic/viz/?cachemiss=true&visualizations[]=map 500 (Internal Server Error)
_prelude.js: Uncaught Error: Cannot find module 'viz/map'
```

If I try opening any data using this new visualization, it appears to not be able to find the .jade file. Even when in the preview before importing, there is a section for javascript, styles, and data, but not Jade template. That leads me to believe that it isn't saving it.

**Comment by colesimmons** [comment]
and the server outputs:
`Error: Cannot find module './map.jade' from '/Users/csimmons/Stash/lightning/tmp/js-build/6cb951e1-ba5b-4914-a3a7-ac8fd9bfe129/viz'`

**Comment by mathisonian** [comment]
Hmm, is the jade file actually contained inside of this folder `/Users/csimmons/Stash/lightning/tmp/js-build/6cb951e1-ba5b-4914-a3a7-ac8fd9bfe129/viz`?

Are the other contents correct?

**Comment by mathisonian** [comment]
I'm starting to suspect this has something to do with the local import functionality, and that if you uploaded it to a secret gist and tried to import using this method:
![screen shot 2015-07-24 at 1 58 00 am](https://cloud.githubusercontent.com/assets/1074773/8868524/761cbbc4-31a7-11e5-950a-7f4c4c404059.png)
 that method the import would be successful, including the `jade` file.

**Comment by colesimmons** [comment]
Nope! There's no jade files in that folder, but all the other contents (js, scss) are correct.

Importing via gist does work. Weird.
