### ISSUE TITLE
The big doc update

### ISSUE THREAD

**Issue by freeman-lab** [lightning-viz/lightning#47]
We've recently added a number of significant features, especially around deployment.

This is to keep track of updates to the documentation page at http://lightning-viz.org/documentation/, based on a plan developed offline with @mathisonian. If anyone has advice on documenting these features, we're open to suggestions!

We probably want the following new sections.

Ways to use a server
- [ ] the standalone app (Mac OS X + Linux)
- [ ] public server at http://public.lightning-viz.org
- [ ] heroku
- [ ] docker
- [ ] local setup with `npm install`

Client-only mode
- [ ] overview + philosophy
- [ ] python example

Developing custom visualizations
- [ ] overview + philosophy (encouraging contributions)
- [ ] environment set up
- [ ] yo generator
- [ ] package structure
- [ ] worked example

In addition, we will change the per-visualization documentation at http://lightning-viz.org/visualizations/ to have a single page per visualization, named by the `npm` module name (e.g. `/lightning-line`), and each will highlight the data schema and client examples, pulled from each repo and stored in `schema.md`, `example.py`, `example.scala`, etc.

- [ ] new visualization pages

**Comment by mathisonian** [comment]
closed by lightning-viz/lightning-viz.github.io#12
