### ISSUE TITLE
Heroku Build Fail

### ISSUE THREAD

**Issue by peterkshultz** [lightning-viz/lightning#48]
Everything was going well until the postinstall began. [This link](https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Flightning-viz%2Flightning&button-url=https%3A%2F%2Fgithub.com%2Flightning-viz%2Flightning) was what I used to deploy on Heroku.

Check a portion of the log out here:

```
149287 verbose rebuildBundles   'vinyl-buffer',
149287 verbose rebuildBundles   'vinyl-source-stream',
149287 verbose rebuildBundles   'webshot',
149287 verbose rebuildBundles   'winston',
149287 verbose rebuildBundles   'yargs' ]
149288 info install lightning-server@0.2.0
149289 info postinstall lightning-server@0.2.0
149290 verbose unsafe-perm in lifecycle true
149291 info lightning-server@0.2.0 Failed to exec postinstall script
149292 error lightning-server@0.2.0 postinstall: `npm run build && npm run fetch-visualizations`
149292 error Exit status 1
149293 error Failed at the lightning-server@0.2.0 postinstall script.
149293 error This is most likely a problem with the lightning-server package,
149293 error not with npm itself.
149293 error Tell the author that this fails on your system:
149293 error     npm run build && npm run fetch-visualizations
149293 error You can get their info via:
149293 error     npm owner ls lightning-server
149293 error There is likely additional logging output above.
149294 error System Linux 3.13.0-57-generic
149295 error command "/tmp/build_ea136ba16860228e3def8af638e5fc80/lightning-viz-lightning-1318f50/vendor/node/bin/node" "/tmp/build_ea136ba16860228e3def8af638e5fc80/lightning-viz-lightning-1318f50/vendor/node/bin/npm" "install" "--userconfig" "/tmp/build_ea136ba16860228e3def8af638e5fc80/lightning-viz-lightning-1318f50/.npmrc"
149296 error cwd /tmp/build_ea136ba16860228e3def8af638e5fc80/lightning-viz-lightning-1318f50
149297 error node -v v0.10.40
149298 error npm -v 1.4.28
149299 error code ELIFECYCLE
149300 verbose exit [ 1, true ]
 !     Push rejected, failed to compile Node.js app
```

Confirmed the issue after failing to deploy twice. Full log available upon request.

Best,

Peter Shultz
University of Michigan

**Comment by mathisonian** [comment]
Thanks @peterkshultz, I'm looking into this.

Could you post the full log in a gist?

**Comment by peterkshultz** [comment]
[Here you are](https://gist.github.com/peterkshultz/2e17d98aee152e6d81c1). Let me know if you need any more assistance. Thanks for the speedy response!

**Comment by mathisonian** [comment]
@peterkshultz it looks like this was failing due to a misconfigured dependency. I've tested and was able to successfully deploy using the link you provided above.

I'll close once you confirm its launching for you

**Comment by peterkshultz** [comment]
I'd call it a partial success. App deploys successfully, although upon deployment it does not work properly:

![new-lightning-herokuapp](https://cloud.githubusercontent.com/assets/5421240/9470886/fef075de-4b1b-11e5-9c44-6209e1339628.png)


Deployed twice to confirm this issue. You can confirm yourself by visiting [the server](https://new-lightning.herokuapp.com).

Would you like me to bring this up in a new issue ticket?

**Comment by mathisonian** [comment]
thanks @peterkshultz. I think we're running into some timeout issues with heroku fetching the visualization modules. 

I'm working on a fix for this, we can keep this issue open to track it

**Comment by mathisonian** [comment]
@peterkshultz after further investigation it seems like stricter type checking in a new version of postgres is causing this (see #49). I'm going to leave this issue open until we fix that but hopefully its relatively straightforward.

**Comment by peterkshultz** [comment]
I look forward to hearing about the eventual bug squash! :sunglasses: 

Thank you for the quick response.

**Comment by mathisonian** [comment]
@peterkshultz, the master branch should have all these fixes in place now. i've just deployed to https://morning-reef-9589.herokuapp.com/ as a test.

note, the build is pretty slow on the free tier of heroku (like ~10 min maybe), but is much faster on paid instances
