### ISSUE TITLE
when running local server, graphics + styles do not render when viewed from another machine on the local network

### ISSUE THREAD

**Issue by micahstubbs** [lightning-viz/lightning#5]
when running local server, graphics + styles do not render when viewed from another machine on the local network

![image](https://cloud.githubusercontent.com/assets/2119400/6087724/8f805e7a-ae14-11e4-9ca6-68093832ea63.png)

**Comment by mathisonian** [comment]
@micahstubbs can you post any errors from the javascript console? It looks like stylesheets aren't being loaded for some reason

**Comment by micahstubbs** [comment]
for reference, Lightning looks great on the host machine

![screen shot 2015-02-06 at 15 30 11](https://cloud.githubusercontent.com/assets/2119400/6087777/34795558-ae15-11e4-9d99-4e6d7d8d9b4b.png)

**Comment by micahstubbs** [comment]
@mathisonian you bet

here are the errors I see on the client machine:
![image](https://cloud.githubusercontent.com/assets/2119400/6087806/7783732e-ae15-11e4-995d-e9978c7565c4.png)

![image](https://cloud.githubusercontent.com/assets/2119400/6087799/68ee13be-ae15-11e4-9e7e-5e151ab16d52.png)

**Comment by micahstubbs** [comment]
beautiful, styles render now on the client machine:

![image](https://cloud.githubusercontent.com/assets/2119400/6088068/3bee8e0e-ae18-11e4-8c40-42d9593c8c52.png)

**Comment by mathisonian** [comment]
fixed in 3efdfbeadba952b4ef8a5744333f1256b1cea64d
