### ISSUE TITLE
Installation takes forever

### ISSUE THREAD

**Issue by dav009** [lightning-viz/lightning#7]
I've played with `lightening-viz` one week ago and got no problems installing it.
However trying to install it today (cloning from master), it seems to get stucked in `npm install`.

It seems to be waiting forever.. I'm not familiar with npm but it seems it is waiting for a package to download. Tried this on two machines.
```
...
npm http 200 https://registry.npmjs.org/view-helpers/-/view-helpers-0.1.5.tgz
npm http 200 https://registry.npmjs.org/topojson/-/topojson-1.6.18.tgz
npm http 200 https://registry.npmjs.org/basic-auth-connect/-/basic-auth-connect-1.0.0.tgz
npm http 200 https://registry.npmjs.org/yargs/-/yargs-1.3.3.tgz
npm http 200 https://registry.npmjs.org/validator/-/validator-3.17.2.tgz
npm http 200 https://registry.npmjs.org/winston/-/winston-0.7.3.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz

```

**Comment by mathisonian** [comment]
@dav009 I'm fairly sure this is related to #8. If you run `npm install -v` it should give more debugging output, and show if things are still happening or the install really has halted

**Comment by dav009** [comment]
Fixed with your last commit :+1:
